
default: &default
  #adapter: sqlite3
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Sakuroot19*
  socket: /tmp/mysql.sock

development:
  <<: *default
  host: 127.0.0.1
  port: 3306
  database: dbIG

test:
  <<: *default
  database: dbIG_T

production:
  <<: *default
  database: dbIG_P
