
default: &default
  adapter: sqlite3
  encoding: utf8


development:
  <<: *default
  host: 127.0.0.1
  port: 3306
  database: dbIG

test:
  <<: *default
  database: dbIG_T

production:
  <<: *default
  database: dbIG_P
